services:
  lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-course-lab-01
    image: ai-course-lab-01:latest
    stdin_open: true
    tty: true
    command: sleep infinity

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
