kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mcp-dev-cluster
nodes:
  # Control plane node with ingress support
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # HTTP
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # HTTPS
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      # Prometheus
      - containerPort: 30090
        hostPort: 30090
        protocol: TCP
      # Grafana
      - containerPort: 30030
        hostPort: 30030
        protocol: TCP
      # Custom MCP servers
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP

  # Worker node 1
  - role: worker
    labels:
      workload: mcp-servers

  # Worker node 2
  - role: worker
    labels:
      workload: monitoring
